version: '2'

services:
  api:
    image: ${REGISTRY}/montagu-api:master
    ports:
     - "8080:8080"
    networks:
     - proxy
    depends_on:
     - db
  db:
    image: ${REGISTRY}/montagu-db:master
    ports:
     - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
    networks:
     - proxy
volumes:
  orderly_volume:
networks:
  proxy: