#!/usr/bin/env bash
ORG=ghcr.io/vimc

if [[ -v "GITHUB_SHA" ]]; then
    GIT_SHA=${GITHUB_SHA:0:7}
else
    GIT_SHA=$(git rev-parse --short=7 HEAD)
fi

if [[ -v "BRANCH_NAME" ]]; then
    GIT_BRANCH=${BRANCH_NAME}
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

# Deal with dependabot tags which look like
#
#   dependabot/npm_and_yarn/app/lodash-4.17.19
#
# But docker does not like
GIT_BRANCH=$(echo $GIT_BRANCH | sed 's;/;-;g')

BUILD_ENV_TAG=$ORG/montagu-api-shared-build-env:$GIT_SHA

# Export env vars needed for running test dependencies
export DB_VERSION=$(<src/config/db_version)
export DB_PORT=5432
export NETWORK=test_nw
export GIT_SHA=$GIT_SHA

# Teardown on exit
function cleanup() {
  set +e
  $HERE/../scripts/stop-database.sh
  $HERE/../scripts/stop-api.sh
  $HERE/../scripts/stop-packit.sh
  docker volume rm montagu_packit_db
  $HERE/../scripts/stop-task-queue.sh
  $HERE/../scripts/stop-proxy.sh
  docker network rm $NETWORK
}
trap cleanup EXIT
