#!/usr/bin/env bash
if [ "$#" -ne 2 ]; then
    echo "Usage: test-db <db-image> <migrate-image>"
    exit 1
fi

set -exu

DB_IMAGE=$1
MIGRATE_IMAGE=$2

HERE=$(realpath $(dirname $0))
$HERE/start-db $DB_IMAGE $MIGRATE_IMAGE db_nw
$HERE/stop-db
