#!/usr/bin/env bash
set -e

if [ "$BUILDKITE" = "true" ]; then
    GIT_ID=${BUILDKITE_COMMIT:0:7}
else
    GIT_ID=$(git rev-parse --short=7 HEAD)
fi

if [ "$BUILDKITE" = "true" ]; then
    GIT_BRANCH=$BUILDKITE_BRANCH
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

ROOT=$(dirname $(dirname $(realpath $0)))

DB_DOCS_PATH=$ROOT/docs/www
DB_DOCS_REPO=`cat $ROOT/docs/destination_repo`

if [ $GIT_BRANCH != "main" ]; then
    echo "Not generating docs for branch $GIT_BRANCH"
    exit 0
fi

if [ -d $DB_DOCS_PATH ]; then
    echo "Updating sources"
    git -C $DB_DOCS_PATH fetch
    git -C $DB_DOCS_PATH checkout main
    git -C $DB_DOCS_PATH reset --hard origin/main
else
    git clone "$DB_DOCS_REPO" $DB_DOCS_PATH
fi

echo "Installing dependencies"
pip3 install --user -r $ROOT/docs/requirements.txt

echo "Generating documentation"
$ROOT/docs/generate.py $GIT_ID $DB_DOCS_PATH

echo "Pushing to github"
git -C $DB_DOCS_PATH push
