steps:
  - label: ":construction_worker: Build shared build env image"
    command: scripts/make-shared-build-env.sh

  - wait

  - label: ":construction_worker: Build integration test image"
    command: scripts/make-integration-test-image.sh

  - label: ":shipit: Build and push main image"
    command: scripts/run-build.sh

  - wait
  # both previous steps are needed to actually run the tests
  - label: ":mag: Run integration tests"
    command: scripts/run-integration-tests.sh
