host: montagu-mq
servers:
  montagu:
    url: https://localhost/api
    user: test.user@example.com
    password: password
  orderlyweb:
    url: https://localhost/reports
  youtrack:
    token: faketoken
  smtp:
    host: smtp.cc.ic.ac.uk
    port: 587
    user: montagu
    password: p@ssword
    from: montagu-notifications@imperial.ac.uk
tasks:
  diagnostic_reports:
    use_additional_recipients: true
    poll_seconds: 5
    reports:
  archive_folder_contents:
    min_file_age_seconds: 3600

