name: 'montagu'

x-logging: &log-journald
  driver: journald
  options:
    tag: montagu

services:
  api:
    image: ${ORG}/montagu-api:master
    ports:
     - "8080:8080"
    networks:
     - proxy
    depends_on:
     - db
    volumes:
     - token_key_volume:/etc/montagu/api/token_key
     - ${PWD}/montagu_emails:/tmp/montagu_emails
  # The stutter in the name is needed to match the constellation deployment,
  # which uses orderly-web as the container prefix, and web as the suffix.
  orderly-web-web:
    image: ${ORG}/orderly-web:master
    networks:
      - proxy
    depends_on:
      - api
    volumes:
      - orderly_volume:/orderly
  packit-app:
    image: mrcide/montagu-packit:main
    networks:
      - proxy
  packit-api:
    image: mrcide/packit-api:main
    networks:
      - proxy
    depends_on:
      packit-db:
        condition: service_healthy
      outpack_server:
        condition: service_started
    environment:
      - PACKIT_OUTPACK_SERVER_URL=http://outpack_server:8000
      - PACKIT_DB_URL=jdbc:postgresql://packit-db:5432/packit?stringtype=unspecified
      - PACKIT_DB_USER=packituser
      - PACKIT_DB_PASSWORD=changeme
      - PACKIT_JWT_SECRET=changesecretkey
      - PACKIT_AUTH_REDIRECT_URL=
      - PACKIT_AUTH_METHOD=preauth
      - PACKIT_JWT_EXPIRY_DAYS=1 # TODO: as part of mrc-9396 - Set this to the same as Montagu token expiry (in seconds)
      - PACKIT_AUTH_ENABLED=true
      - PACKIT_AUTH_GITHUB_ORG=none
      - PACKIT_AUTH_GITHUB_TEAM=none
  packit-db:
    image: mrcide/packit-db:main
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wait-for-db"]
  outpack_server:
    image: mrcide/outpack_server:main
    volumes:
      - ./../packit/demos/orderly:/outpack # This requires packit repo to be cloned in same dir as montagu-proxy!
    networks:
      - proxy
  db:
    image: ${ORG}/montagu-db:master
    ports:
     - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
    networks:
     - proxy
  orderly:
    image: ${ORG}/orderly.server:master
    volumes:
      - orderly_volume:/orderly
    command: --port 8321 --go-signal /orderly_go /orderly
    networks:
      - proxy
  contrib:
    image: ${ORG}/montagu-contrib-portal:master
    networks:
     - proxy
    depends_on:
     - api
    volumes:
     - template_volume:/usr/share/nginx/html/templates
     - guidance_volume:/usr/share/nginx/html/guidance
  admin:
    image: ${ORG}/montagu-admin-portal:master
    networks:
     - proxy
    depends_on:
     - api
volumes:
  orderly_volume:
  template_volume:
  guidance_volume:
  token_key_volume:
networks:
  proxy:
