name: 'montagu'

x-logging: &log-journald
  driver: journald
  options:
    tag: montagu

services:
  api:
    image: ${ORG}/montagu-api:master
    ports:
     - "8080:8080"
    networks:
     - proxy
    depends_on:
     - db
    volumes:
     - token_key_volume:/etc/montagu/api/token_key
     - ${PWD}/montagu_emails:/tmp/montagu_emails

  # The stutter in the name is needed to match the constellation deployment,
  # which uses orderly-web as the container prefix, and web as the suffix.
  #orderly-web-web:
  #  image: ${ORG}/orderly-web:master
  #  networks:
  #   - proxy
  #  depends_on:
  #    - api
  #  volumes:
  #   - orderly_volume:/orderly
  db:
    image: ${ORG}/montagu-db:master
    ports:
     - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
    networks:
     - proxy
  orderly:
    image: ${ORG}/orderly.server:master
    volumes:
     - orderly_volume:/orderly
    command: --port 8321 --go-signal /orderly_go /orderly
    networks:
     - proxy
  contrib:
    image: ${ORG}/montagu-contrib-portal:master
    networks:
     - proxy
    depends_on:
     - api
    volumes:
     - template_volume:/usr/share/nginx/html/templates
     - guidance_volume:/usr/share/nginx/html/guidance
  admin:
    image: ${ORG}/montagu-admin-portal:master
    networks:
     - proxy
    depends_on:
     - api
volumes:
  orderly_volume:
  template_volume:
  guidance_volume:
  token_key_volume:
networks:
  proxy:
