services:
  mq:
    image: redis
    ports:
      - "6379:6379"
  flower:
    image: mher/flower:0.9.5
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://montagu-mq-1//
      - CELERY_RESULT_BACKEND=redis://montagu-mq-1/0
      - FLOWER_PORT=5555
  api:
    # TODO: switch to main when branch is merged
    image: ghcr.io/vimc/montagu-api:update-repo
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: ghcr.io/vimc/montagu-db:main
    ports:
      - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
  contrib:
    image: ghcr.io/vimc/montagu-contrib-portal:main
    depends_on:
      - api
  admin:
      image: ghcr.io/vimc/montagu-admin-portal:main
      depends_on:
        - api
  smtp_server:
    image: reachfive/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"
