#!/usr/bin/env bash
ORG=vimc

if [ "$BUILDKITE" = "true" ]; then
    GIT_SHA=${BUILDKITE_COMMIT:0:7}
else
    GIT_SHA=$(git rev-parse --short=7 HEAD)
fi

if [ "$BUILDKITE" = "true" ]; then
    GIT_BRANCH=$BUILDKITE_BRANCH
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

# Deal with dependabot tags which look like
#
#   dependabot/npm_and_yarn/app/lodash-4.17.19
#
# But docker does not like
GIT_BRANCH=$(echo $GIT_BRANCH | sed 's;/;-;g')

SHARED_BUILD_ENV_TAG=$ORG/montagu-reverse-proxy-shared-build-env:$GIT_SHA
INTEGRATION_TESTS_TAG=$ORG/montagu-reverse-proxy-integration-tests:$GIT_SHA
BRANCH_TAG=$ORG/montagu-reverse-proxy:$GIT_BRANCH
SHA_TAG=$ORG/montagu-reverse-proxy:$GIT_SHA
