name: api
on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: ~

defaults:
  run:
    working-directory: ./api/src

env:
  NETWORK: test_nw
  DB_PORT: 5432

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.4.2'
      - name: Install libsodium
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libsodium23
      - name: Check schema
        run: ./gradlew :validateSchema -i
      - name: Run test dependencies
        # NB These scripts currently run main/master images - we should eventually provide at least the option to run against
        # current branch of deps
        #./start-api.sh
        #./start-proxy.sh
        #./start-task-queue.sh
        working-directory: ./api/scripts
        run: |
          ./start-database.sh
          ./start-packit.sh docker-packit
      - name: Generate test data
        run: |
          ./gradlew :generateTestData:installDist
          ./gradlew :userCLI:installDist
          ./generateTestData/generate.sh
      - name: Run tests
        run: ./gradlew :testLibrary

