name: clean-packit.yml
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: ~

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out source
        uses: actions/checkout@v4
      - run: java -version
      - name: start packit
        working-directory: ./api/scripts
        run: ./start-packit.sh docker-packit
      - run: docker ps
      - run: docker logs montagu-packit-api
