name: Database Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_PAT }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/vimc/montagu-db
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value=${{ github.head_ref }},enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=branch
            type=sha,prefix=
        env:
          # By default the SHA for PRs would refer to the temporary merge
          # commit. We want the PR's head sha instead, since it is more useful.
          DOCKER_METADATA_PR_HEAD_SHA: 1
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: true
          file: ./db/Dockerfile
          context: ./db
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
